version: "3.8"
services:
  dev:
    build: site
    ports:
      - "5000:5000"
    volumes:
      - ./site:/app
      - /app/node_modules
  win_dev:
    build:
      context: site
      dockerfile: Dockerfile.win
    ports:
      - "5000:5000"
    volumes:
      - ./site:/app
      - /app/node_modules
